---
title: "Milestone-5"
author: "George Guarnieri"
date: "10/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About Page
The data for my final project comes from Harvard Student Agencies. With over 650 undergraduate employees, Harvard Student Agencies is the largest student run business in the world. Harvard Student Agencies has several subsidiaries, with the largest being the Harvard Shop. This coming year, I will be serving as the Managing Director  of the Harvard Shop, and, thus, oversee all aspects of the business. The Harvard Shop has three physical locations, as well as an ecommerce platform. The Harvard Shop records its sales data in two different ways, since it has two different point of sale platforms. The first point of sale system, Vend, is utilized in the physical locations and is simultaneously used as an inventory tracking system. The online store uses a separate point of sale system, Shopify, which sinks its inventory count with that of Vend.

For my final project, I will be focusing on data from both of these points of sales systems. The data can be exported from Vend and Shopify in CSV format and is already cleaned. The main focus on my project will be the Harvard Shop’s Web Sales, and how they can best be improved. The different variables that I have available include Month (Includes both the month and year), Fulfillment Status (states whether or not the given order was fulfilled), Customer Type (provides a tag for the given customer), Product Price (provides the price of the product, Product Title, Average Order Value (gives the average order value for the full order), Discounts (gives the total discounted amount), Returns (gives the total amount of returns), Total Cost (provides the cost of goods sold), and Gross Profit (gives the sale value minus the cost of goods sold). I have obtained the data from October of 2016 through October of 2019. I hope to identify key trends throughout this period, which will allow for changes to be made to our web processes and site in order to maximize revenue growth.

In particular, one of the main hopes that I have is that this data will better inform decisions about which items should be pushed the hardest through our marketing campaigns, how we can best optimize our product mix, how we can best optimize our procurement process, and lastly how we can optimize our site based on on the combination of all of these different insights. More specifically, in terms of what changes we'd be able to make, we would be able to properly utilize our adspend in the most efficient way possible, as well as to change the way that this adspend corresponds to potential changes in our site.

As far as the procurement process goes, any changes we can make to our system that would prevent us from purchasing products that have fairly low sell through rates would be very useful. One of the largest problems that currently exists in The Harvard Shop is the procurement of products without actually considering how any given product will sell. 



